POST https://quote2cash-api.onrender.com/api/Auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "adminpass"
}


### Get Quotes
GET https://quote2cash-api.onrender.com/api/Quotes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImNhOTUyYzIyLTc4MDYtNGRlMC1hZDAzLTE3ZmYwNjY2OWE1ZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzgxNjE2OTQ0LCJpc3MiOiJRdW90ZTJDYXNoIiwiYXVkIjoiUXVvdGUyQ2FzaFVzZXJzIn0.LJjDzqmvBMtz1lS2CqhPtDiGdANDs2eHKTJkzT1ocw0

### Get Quote next-number
GET https://quote2cash-api.onrender.com/api/Quotes/next-number
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImNhOTUyYzIyLTc4MDYtNGRlMC1hZDAzLTE3ZmYwNjY2OWE1ZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzgxNjE2OTQ0LCJpc3MiOiJRdW90ZTJDYXNoIiwiYXVkIjoiUXVvdGUyQ2FzaFVzZXJzIn0.LJjDzqmvBMtz1lS2CqhPtDiGdANDs2eHKTJkzT1ocw0