POST http://localhost:5227/api/Auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "adminpass"
}


### Get Quotes
GET http://192.168.8.103:5227/api/Quotes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjgwYzIzMzkzLTkyYjgtNGQ3NC05YTcyLTkyNjVhOGU5Yjc2ZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzgxMzQxMTY2LCJpc3MiOiJRdW90ZTJDYXNoIiwiYXVkIjoiUXVvdGUyQ2FzaFVzZXJzIn0.SB5JAsMugpjNm1zSnw0qDMeH4tsrSY7vKQZnrvuE0GQ

### Get Quote next-number
GET http://192.168.8.103:5227/api/Quotes/next-number
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjgwYzIzMzkzLTkyYjgtNGQ3NC05YTcyLTkyNjVhOGU5Yjc2ZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzgxMzQxMTY2LCJpc3MiOiJRdW90ZTJDYXNoIiwiYXVkIjoiUXVvdGUyQ2FzaFVzZXJzIn0.SB5JAsMugpjNm1zSnw0qDMeH4tsrSY7vKQZnrvuE0GQ

### Get Quote Item Image
GET http://localhost:4173/api/quotes/items/images/Q9026060013_1.jpeg
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImNhOTUyYzIyLTc4MDYtNGRlMC1hZDAzLTE3ZmYwNjY2OWE1ZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzg0NTQ2MDAyLCJpc3MiOiJRdW90ZTJDYXNoIiwiYXVkIjoiUXVvdGUyQ2FzaFVzZXJzIn0.OwbOfL6fTrG9NsN70AXcQBx-aOGRftMj-QNZ8ZPnmGE