POST http://localhost:5227/api/Auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "adminpass"
}

### Get Image
GET http://localhost:5227/api/tools/images/tool_69f6d849-eff5-4b38-bd42-7e580e29274d.jpeg
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImNhOTUyYzIyLTc4MDYtNGRlMC1hZDAzLTE3ZmYwNjY2OWE1ZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzg0Nzk1MzI5LCJpc3MiOiJRdW90ZTJDYXNoIiwiYXVkIjoiUXVvdGUyQ2FzaFVzZXJzIn0.p9gbz9elTD-ECc_CtDASJi-51Fo_LvEsWAF4hKTJNbg