deployment:
  tasks:
    - export DEPLOY_PATH=/home/biturvnu/public_html/staging_erp_biture
    - /bin/cp -r * $DEPLOY_PATH
    - cd $DEPLOY_PATH
    - npm install
    - npm run build -- --mode staging
