### Test Login Endpoint
POST http://localhost:5227/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "adminpass"
}

### Test Login Endpoint
POST https://api.erp.biture.co.za/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "adminpass"
}
