### Test Login Endpoint
POST https://api.erp.biture.co.za/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "adminpass"
}

### Ping

GET https://api.erp.biture.co.za/api/ping
Content-Type: application/json

